config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path(@article)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<body>
  <h1>Edit article</h1>
  <div>
    <%= form_for(@article) do |f| %>
    <div class="form-inputs">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="form-inputs">
      <%= f.label :content %>
      <%= f.text_field :content %>
    </div>
      <a class="btn-design"><%= f.submit %></a>
    <% end %>
  </div>
  <%=link_to "Back to main page", articles_path%>
</body>

app/views/articles/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button><%=link_to "Add a new article", new_article_path%></button>
  </nav>
</nav>

<body>
  <ul>
    <% @articles.each do |article| %>
      <article>
        <a><%= link_to article.title, article_path(article)%></a>
      </article>
    <% end %>
  </ul>

</body>

app/views/articles/new.html.erb
<body>
  <h1>New article</h1>
  <div>
    <%= form_for(@article) do |f| %>
    <div class="form-inputs">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="form-inputs">
      <%= f.label :content %>
      <%= f.text_field :content %>
    </div>
      <a class="btn-design"><%= f.submit %></a>
    <% end %>
  </div>
  <%=link_to "Back to main page", articles_path%>
</body>

app/views/articles/show.html.erb
<h3><%= "#{@article.title}" %></h3>

<p><%= @article.content%></p>

<button><%=link_to "Back to main page", articles_path%></button>


<a <% href="/articles/#{@article.id}/edit">
  <i class="fa fa-pencil">
  </i>
</a>%>>

<button>
  <%= link_to "🗑",
    article_path(@article),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>